server:
  error:
    include-message: always
  forward-headers-strategy: framework
  port: 18081
  servlet:
    context-path: /fireman

spring:
  application:
    name: service
  jackson:
    deserialization:
      accept-float-as-int: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com