remote_theme: ddc-java/ddc-day-book
repository_link:
  enabled: false
page_navigator:
  enabled: true
titles_from_headings:
  enabled: false
prev_next_navigation:
- bottom

title: "Fireman"
description: "As a Fireman, extinguish the flames the Arsonist creates."

author:
  name: "Christian Gonzalez, Matthew Page"

# Do not change the following line.
  copyright: true
